openapi: 3.0.3
info:
  title: Girik Marine Backend API
  description: |
    Production-grade API documentation for Girik Marine Backend.
    Use role-specific docs: `/api-docs/admin`, `/api-docs/gm`, `/api-docs/tm`, `/api-docs/surveyor`, `/api-docs/client`
  version: 1.0.0
  contact:
    name: Girik Marine

servers:
  - url: http://localhost:3000
    description: Local development
  - url: /
    description: Relative (same host)

security:
  - bearerAuth: []

tags:
  - name: Auth
    description: Authentication and session management
  - name: Jobs
    description: Job lifecycle management
  - name: Vessels
    description: Vessel registry and management
  - name: Certificates
    description: Certificate management and verification
  - name: Payments
    description: Payment and invoice management
  - name: Dashboard
    description: Role-based dashboard data
  - name: Clients
    description: Client management
  - name: Health
    description: Health check

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT token from login. Use in header: Authorization: Bearer &lt;token&gt;"
  schemas: {}
