openapi: 3.0.3
info:
  title: Girik Marine Backend API
  description: |
    Production-grade API documentation for Girik Marine Backend.
    Use role-specific docs: `/api-docs/admin`, `/api-docs/gm`, `/api-docs/tm`, `/api-docs/surveyor`, `/api-docs/client`
  version: 1.0.0
  contact:
    name: Girik Marine

servers:
  - url: http://localhost:3000
    description: Local development
  - url: /
    description: Relative (same host)

security:
  - bearerAuth: []

tags:
  - name: Auth
    description: Authentication and session management
  - name: Public
    description: Public APIs (no auth)
  - name: Jobs
    description: Job lifecycle management
  - name: Vessels
    description: Vessel registry and management
  - name: Certificates
    description: Certificate management and verification
  - name: Payments
    description: Payment and invoice management
  - name: Dashboard
    description: Role-based dashboard data
  - name: Clients
    description: Client management
  - name: Health
    description: Health check
  - name: Surveys
    description: Survey management
  - name: Surveyors
    description: Surveyor management
  - name: Checklists
    description: Checklist operations
  - name: Checklist Templates
    description: Checklist template management
  - name: Support
    description: Support tickets
  - name: Search
    description: Global search
  - name: Compliance
    description: Compliance and data export
  - name: Notifications
    description: User notifications
  - name: Users
    description: User management
  - name: Documents
    description: Document upload and management
  - name: System
    description: System administration
  - name: Reports
    description: Reports
  - name: Non-Conformities
    description: NC management
  - name: TOCA
    description: Transfer of Class
  - name: Flags
    description: Flag administration
  - name: Approvals
    description: Approval workflows
  - name: Change Requests
    description: Change requests
  - name: Certificate Templates
    description: Certificate template management
  - name: Incidents
    description: Incident reporting
  - name: Activity Requests
    description: Activity planning requests
  - name: Providers
    description: Service provider management
  - name: Feedback
    description: Customer feedback
  - name: Mobile
    description: Mobile app sync

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT token from login. Use in header: Authorization: Bearer &lt;token&gt;"
  schemas: {}
