import fs from 'fs';
import path from 'path';

const managementDir = './src/modules/management';
const outputFile = './src/modules/management/MANAGEMENT_API_GUIDE.md';

function scanDir(dir, results = []) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            scanDir(fullPath, results);
        } else if (file.endsWith('.routes.js')) {
            const content = fs.readFileSync(fullPath, 'utf8');
            const lines = content.split('\n');
            let currentPathPrefix = '';

            // Try to find router.use or similar if nested, but usually management routes are flat in routes.js
            // For now, extract direct router.get/post etc.

            lines.forEach(line => {
                const match = line.match(/router\.(get|post|put|delete|patch)\(['"](.*?)['"](.*?)\)/);
                if (match) {
                    const method = match[1].toUpperCase();
                    const endpoint = match[2];
                    const rest = match[3];

                    // Look for hasRole in the rest of the line
                    const roleMatch = rest.match(/hasRole\((.*?)\)/);
                    let roles = 'N/A';
                    if (roleMatch) {
                        roles = roleMatch[1].replace(/['"]/g, '');
                    } else if (line.includes('authenticate')) {
                        roles = 'Any Auth User';
                    }

                    // Get comment above for description
                    const lineIndex = lines.indexOf(line);
                    let description = 'No description';
                    if (lineIndex > 0 && lines[lineIndex - 1].trim().startsWith('//')) {
                        description = lines[lineIndex - 1].trim().replace('//', '').trim();
                    }

                    results.push({
                        module: path.basename(dir),
                        method,
                        endpoint,
                        roles,
                        description
                    });
                }
            });
        }
    }
    return results;
}

const apis = scanDir(managementDir);

let markdown = `# Management Module API Guide\n\n`;
markdown += `This guide is auto-generated by scanning \`.routes.js\` files.\n\n`;
markdown += `## Complete Operational API Matrix\n\n`;
markdown += `| Module | Method | Endpoint | Access Roles | Description |\n`;
markdown += `| :--- | :--- | :--- | :--- | :--- |\n`;

apis.forEach(api => {
    markdown += `| ${api.module} | ${api.method} | \`${api.endpoint}\` | **${api.roles}** | ${api.description} |\n`;
});

fs.writeFileSync(outputFile, markdown);
console.log(`Updated ${outputFile}`);
